version: '3.7'

services:
  mysql:
    build: ./mysql
    container_name: my_mysql
    restart: on-failure
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
